# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  watch:
    action: started
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_URL: ${{env.GITHUB_SERVER_URL}}/${{env.GITHUB_REPOSITORY}}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Someone stars **${{env.REPO_NAME}}** repository, see [here](${{env.REPO_URL}}).
          format: markdown
