# This is a basic workflow to help you get started with Actions

name: Repo Star Notify

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: '0 0 * * 6' # 每周星期天8点实行一次
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Star Count
        id: repo-stars
        uses: alanhg/repo-star-count-action@master
      - name: Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            About repository [${{ github.event.repository.name }}](https://github.com/${{ github.repository }}).
            There are currently ${{steps.repo-stars.outputs.stars}}⭐, come on!
          format: markdown
